# Base Image
FROM golang:1.13.9

# Work directory
WORKDIR /go/src/github.com/wkmkymt/go-todo-api/app

# Install Packages
RUN curl -fLo /go/bin/air https://git.io/linux_air \
  && chmod +x /go/bin/air
